<div id='contenedormayor'>
	<div id='contenedor'>
		<div id='mensaje'>
			[[<span id='corchete'>MANTENIMIENTO DE ARTICULOS</span>]]  
		</div>
		<div id='espaciovacio'></div>
		<div id='addnew'>
			<a href="articulos/new">AGREGAR</a>
		</div>
		<div id='contenido'></div>
		<?
		include('clases/paginacion.class.php');
		$pag = new Paginacion();
		$pag->getPaginas(10);
		$pag->getPage($page);
		$pag->getConsulta("SELECT * FROM articulos where estado =1 ORDER BY CODIGO DESC");
		$pag->getUrl("/ventas/maestros/articulos/");
		if(!$pag->query){
			//$this->queryError;
		}else{
		?>
			<div id='contendentro'>
				<table>
					<thead>
						<tr>
							<th width='30px'>CODIGO</th>
							<th>ARTICULO</th>
							<th>MARCA</th>
							<th>MODELO</th>
							<th width='120px'>PROVEEDOR</th>
							<th width='100px'>PRECIO</th>
							<th >OBERSACION</th>
							<th width='10px'>S</th>
							<th width='10px'>M</th>
							<th width='10px'>E</th>
						</tr>
					</thead>
					<tbody>
						<? foreach($pag->resultado as $resulta){ ?>
						<tr>
							<td align='center'><? echo $resulta['codigo']; ?></td>
							<td><? echo $resulta['articulo']; ?></td>
							<td><? echo $resulta['marca']; ?></td>
							<td><? echo $resulta['modelo']; ?></td>
							<td><? echo $resulta['id_provee']; ?></td>
							<td align=right><? echo $resulta['precio']; ?></td>
							<td><? echo $resulta['observacion']; ?></td>
							<td>
								<a href="">
								<img src='/ventas/imagen/stock.png'>
								</a>
							</td>
							<td>
								<a href="articulos/edit/<? echo $resulta['codigo'];?>">
								<img src='/ventas/imagen/database_edit.png'>
								</a>
							</td>
							<td>
								<a href="javascript:deleteID('<? echo $resulta['codigo'];?>','articulos')">
								<img src='/ventas/imagen/delete.png'>
								</a>
							</td>
						</tr>
						<? } ?>
					</tbody>
				</table>
				<!-- INICIO DE PAGINACION -->
				<table>
					<thead>
						<tr>
							<th>
							<? $pag->verPaginacion(); ?>
							</th>
						</tr>
					</thead>
				</table>
				<!-- FIN DE PAGINACION -->
			</div>
		<?}?>
	</div>
</div>